name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lhci:
    name: Web Stats Reporter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}

      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.6.x
          lhci autorun

      - name: Webstats Lighthouse reporter
        id: webstats-lighthouse-reporter
        uses: ./.github/actions/webstats-lighthouse-reporter
        env:
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.number }}
          WEBSTATS_PROJECT_ID: ${{ secrets.WEBSTATS_PROJECT_ID }}
          WEBSTATS_API_KEY: ${{ secrets.WEBSTATS_API_KEY }}